export interface ProducerConfig {
    /**
     * A list of host/port pairs to use for establishing the initial connection to the Kafka cluster
     * Format: 'host1:port1,host2:port2,...'
     */
    bootstrapServers: string;
    
    /**
     * Client identifier
     */
    clientId?: string;
    
    /**
     * Maximum time in milliseconds the producer will wait for a response to a request
     */
    requestTimeout?: number;
    
    /**
     * The maximum size of a request in bytes
     */
    maxRequestSize?: number;
    
    /**
     * The number of acknowledgments the producer requires from the server before considering a request complete
     * 0 = no acknowledgments
     * 1 = only the leader acknowledges
     * -1 or 'all' = all in-sync replicas acknowledge
     */
    acks?: number | 'all';
    
    /**
     * The maximum number of unacknowledged requests the client will send on a single connection
     */
    maxInFlightRequestsPerConnection?: number;
    
    /**
     * The total bytes of memory the producer can use to buffer records waiting to be sent to the server
     */
    bufferMemory?: number;
    
    /**
     * The default batch size in bytes when batching multiple records sent to a partition
     */
    batchSize?: number;
    
    /**
     * The amount of time to wait before sending a batch when using batch processing
     */
    lingerMs?: number;
    
    /**
     * Compression type for all data generated by the producer
     */
    compressionType?: 'none' | 'gzip' | 'snappy' | 'lz4';
    
    /**
     * How many times to retry sending a failing message
     */
    retries?: number;
    
    /**
     * Backoff time in milliseconds between retries
     */
    retryBackoffMs?: number;
  
    /**
     * Name of the partitioner to use for determining which partition to send records to
     */
    partitionerClass?: string;
  }
  